version: '3.8'

services:
  streamlit_app:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    command: streamlit run /app/main.py
    hostname: batedores
    ports:
      - "9101:8501"
    volumes:
      - ./mnt/1tb/Pi86/:/tmp
    working_dir: /tmp
    environment:
      - PYTHONUNBUFFERED=1

  static_server:
    image: python:3.11-slim
    command: python -m http.server 8000
    hostname: batedores-cdn
    ports:
      - "9102:8000"
    volumes:
      - ./mnt/1tb/Pi86/:/tmp
    working_dir: /tmp
    environment:
      - PYTHONUNBUFFERED=1
